### ISSUE TITLE
Dica: Nunca coloque o DB puro no GitHub

### ISSUE THREAD

**Issue by vmesel** [ThiagoLopes/ReportToEasy#1]
Thiagão, tudo bem parceiro?

Tenho uma dica pra te dar, nunca coloque o db no github, isso pode ser as vezes uma fatalidade para as suas senhas. Existem diversos projetos que você coloca o db e junto com ele vem senhas masters de usuários de servidores que existem. Tome cuidado.

Caso esteja usando uma ORM ensine as pessoas a usarem o create db, mas caso você esteja fazendo tudo na mão, recomendo que você crie um arquivo SQL que tenha todas as suas tabelas deste banco!

**Comment by thiagolopes** [comment]
Opá! Obrigado pele feed!
Estou sim usando ORM e irei no próximo commit deixar mais claro no README os passos para o create db e tambem retirar o db do projeto.

Obrigado @vmesel !
